/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.*;
import entidades.ClienteNombre;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import logica.ClienteBL;

/**
 *
 * @author R000R
 */
public class FrmListarCliente extends javax.swing.JFrame {   
      /**
     * Creates new form frmCode
     */
    public FrmListarCliente() {
        initComponents();
        this.listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbtNombre = new javax.swing.JRadioButton();
        rbtCiudad = new javax.swing.JRadioButton();
        rbtCodigo = new javax.swing.JRadioButton();
        rctPaterno = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rbtNombre);
        rbtNombre.setText("Nombre");
        rbtNombre.setActionCommand("rbnombre");
        rbtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNombreActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtCiudad);
        rbtCiudad.setText("Ciudad");
        rbtCiudad.setActionCommand("rbciudad");
        rbtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCiudadActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtCodigo);
        rbtCodigo.setText("Codigo");
        rbtCodigo.setActionCommand("rbCodigo");
        rbtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCodigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rctPaterno);
        rctPaterno.setText("A Paterno");
        rctPaterno.setActionCommand("rbdireccion");
        rctPaterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rctPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rctPaternoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ordenamiento");

        Eliminar.setText("BORRAR");
        Eliminar.setActionCommand("btnborrar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Modificar.setText("MODIFICAR");
        Modificar.setActionCommand("btnguardar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane2.setViewportView(tabla1);
        tabla1.getAccessibleContext().setAccessibleName("tabla");

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(rbtCodigo)
                                .addGap(18, 18, 18)
                                .addComponent(rbtNombre)
                                .addGap(18, 18, 18)
                                .addComponent(rctPaterno)
                                .addGap(25, 25, 25)
                                .addComponent(rbtCiudad))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(Modificar)
                                .addGap(105, 105, 105)
                                .addComponent(Eliminar)
                                .addGap(131, 131, 131)
                                .addComponent(jButton4)))
                        .addGap(0, 202, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtNombre)
                            .addComponent(rbtCodigo)
                            .addComponent(rbtCiudad)
                            .addComponent(rctPaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(Eliminar))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Modificar)
                        .addGap(60, 60, 60))))
        );

        rctPaterno.getAccessibleContext().setAccessibleName("rbdireccion");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNombreActionPerformed
        Collections.sort(cliente,new ClienteNombre());
        this.listar();
    }//GEN-LAST:event_rbtNombreActionPerformed

    private void rbtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCodigoActionPerformed
        Collections.sort(cliente);
        this.listar();
    }//GEN-LAST:event_rbtCodigoActionPerformed

    private void rctPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rctPaternoActionPerformed
        Collections.sort(cliente,new ClientePaterno());
        this.listar();
    }//GEN-LAST:event_rctPaternoActionPerformed

    private void rbtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCiudadActionPerformed
        Collections.sort(cliente,new ClienteCiudad());
        this.listar();
    }//GEN-LAST:event_rbtCiudadActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
       ii= tabla1.getSelectedRow();
       if(ii>-1){
           modelo=(DefaultTableModel)tabla1.getModel();
           codigo=(String)modelo.getValueAt(ii, 0);           
            nombre = (String)modelo.getValueAt(ii,1);
            ciudad = (String)modelo.getValueAt(ii,2);
            direccion = (String)modelo.getValueAt(ii,3);
            telefono=(String)modelo.getValueAt(ii, 4);           
            dni = (String)modelo.getValueAt(ii,5);
            apaterno = (String)modelo.getValueAt(ii,6);
            amaterno = (String)modelo.getValueAt(ii,7);
            email = (String)modelo.getValueAt(ii,8);
             client= new Cliente(codigo,nombre,ciudad,direccion,telefono,dni,apaterno,amaterno,email);
             FrnModificarCliente f= new  FrnModificarCliente(this,client);
             f.setVisible(true);
           
       } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el registro a modificar", "Aviso", 2);             
        }
        
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        
        int respuesta;
        int i = tabla1.getSelectedRow();
        if (i>-1) {
            respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea eliminar el registro?", 
                    "Aviso", JOptionPane.YES_NO_OPTION, 3);
            if(respuesta == JOptionPane.OK_OPTION) {
                modelo=(DefaultTableModel)tabla1.getModel();
                codigo = (String)modelo.getValueAt(i,0);
                mensaje = ClienteBL.eliminarCliente(codigo);
                if(mensaje.compareTo("Registro eliminado")==0) {
                    JOptionPane.showMessageDialog(this, mensaje, "Resultado", 1);
     //               rbtCodigoActionPerformed(evt);
                }
                else
                    JOptionPane.showMessageDialog(this, mensaje, "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el registro a modificar", "Aviso", 2);             
        }
        
        
    }//GEN-LAST:event_EliminarActionPerformed
   
    private  void listar(){   
        modelo=new DefaultTableModel();   
        ArrayList<Cliente> cliente = ClienteBL.listarCliente();
        Object  data[] = new Object[cliente.size()];        
        modelo.setColumnIdentifiers(columnas);       
       // modelo.addColumn(column);
        Iterator<Cliente> iterador=cliente.iterator();
        int i=0;
        while(iterador.hasNext()){
            client = iterador.next();            
            data[0]=client.getCodigo();          
            data[1]=client.getNombre();
            data[2]=client.getCiudad();          
            data[3]=client.getDireccion();    
            data[4]=client.getTelefono();
            data[5]=client.getDni();
            data[6]=client.getApaterno();          
            data[7]=client.getAmaterno();    
            data[8]=client.getEmail();
            modelo.addRow(data);
            i++;
         }
        tabla1.setModel(modelo);
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {         
             new FrmListarCliente().setVisible(true);
               
            }
        });
    }   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Modificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtCiudad;
    private javax.swing.JRadioButton rbtCodigo;
    private javax.swing.JRadioButton rbtNombre;
    private javax.swing.JRadioButton rctPaterno;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
   private ArrayList<Cliente> cliente;
    private DefaultTableModel modelo;
    private String columnas[] = {"Código", "Nombre", "Ciudad", "Dirección", "Telefono"
            ,"Dni","Apellido Paterno","Apellido Materno","Email"};
    private Object fila[] = new Object[columnas.length];
    private Cliente client = null;
    private Iterator<Cliente> iterador;
   
    String codigo,nombre,ciudad,direccion,telefono,dni,apaterno,amaterno,email,mensaje;
    int ii;
}
